### ISSUE TITLE
Unexpected Error  FileExistsError: [Errno 17] File exists: '/root/kodi.proxy/addon_data/script.module.slyguy

### ISSUE THREAD

**Issue by trent0579** [matthuisman/kodi.proxy#20]
Hi Matt,

Thanks for all your good work.

I am hoping to use Kodi.Proxy to watch the 9Now streams in Channels DVR via TVheadend.

I have installed Kodi.Proxy via the command line in Debian and Ubuntu and I am getting the error below when trying to log in using the 9Now plugin. I have also tried installing Kodi.Proxy using your dockerfile and I am getting the same error.

Woud you be able to assist?

plugin://slyguy.9now/?_=login

slyguy.9now (0.3.8): Installed

9Now (0.3.8/0.85.23) (19.2 kodi.proxy x86_64) - Unexpected Error
 FileExistsError: [Errno 17] File exists: '/root/kodi.proxy/addon_data/script.module.slyguy'

  File "<frozen os>", line 225, in makedirs
  File "util.py", line 761, in makedirs
    xbmcvfs.mkdirs(path)
  File "database.py", line 178, in connect
    makedirs(os.path.dirname(self.database))
  File "db_storage.py", line 37, in get
    for row in Settings.select().where(Settings.addon_id.in_((ADDON_ID, COMMON_ADDON_ID))):
  File "types.py", line 150, in _get_value_owner
    owner, value = STORAGE.get(self.owner, self._id, inherit=self._inherit)
  File "types.py", line 136, in value
    value = self._get_value_owner()[1]
  File "types.py", line 402, in migrate
    if settings.MIGRATED.value:
  File "types.py", line 547, in get_setting
    migrate(self)
  File "types.py", line 528, in get
    return self.get_setting(key, default).value
  File "session.py", line 407, in __init__
    super(Session, self).__init__(verify=settings.getBool('verify_ssl', True) if verify is None else verify,
  File "api.py", line 12, in new_session
    self._session = Session(HEADERS, base_url=API_URL)
  File "plugin.py", line 20, in before_dispatch
    api.new_session()
  File "signals.py", line 47, in emit
    f(*args, **kwargs)
  File "router.py", line 129, in dispatch
    signals.emit(signals.BEFORE_DISPATCH)
  File "signals.py", line 53, in throwable
    yield
 [OK]
Exception ignored in: <function RawSession.__del__ at 0x730afea43e20>
Traceback (most recent call last):
  File "/root/kodi.proxy/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 313, in __del__
    self.close()
  File "/root/kodi.proxy/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 308, in close
    super(RawSession, self).close()
  File "/root/kodi.proxy/addons/slyguy.dependencies/resources/modules/requests/sessions.py", line 736, in close
    for v in self.adapters.values():
             ^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute 'adapters'
**** time: 33.169 s *****

**Comment by matthuisman** [comment]
should be now fixed with [fix mkdirs](https://github.com/matthuisman/kodi.proxy/commit/68993583ebdb3f22453e4ea2e54dabaf062934d3)
git pull latest code for kodi.proxy :)
