### ISSUE TITLE
Unable to add EPG from addons

### ISSUE THREAD

**Issue by AltFreq07** [matthuisman/kodi.proxy#7]
Currently unable to add any EPG data from the addons to IPTV Merge. The live channels themselves work fine after adding via the playlist.

Heres my output with debugging turned on.

```
:~/kodi.proxy$` ./proxy

0: install
1: uninstall
2: update
3: plugin
4: settings

Select: 3

0: slyguy.7plus
2: plugin.program.iptv.merge
4: script.module.slyguy

Select: 2

plugin://plugin.program.iptv.merge

DEBUG - Calling plugin.program.iptv.merge default ['plugin://plugin.program.iptv.merge/', 1, '', 'resume:false']
DEBUG - plugin.program.iptv.merge - SIGNAL: before_dispatch
DEBUG - plugin.program.iptv.merge - Router Parsed: '' => home {'_url': ''}
DEBUG - WARNING: Missing /home/vpn/kodi.proxy/addons/pvr.iptvsimple/addon.xml
DEBUG - WARNING: Missing /home/vpn/kodi.proxy/addons/pvr.iptvsimple/resources/settings.xml
DEBUG - WARNING: Missing /home/vpn/kodi.proxy/addons/pvr.iptvsimple/resources/language/resource.language.en_gb/strings.po
Title:
Content: videos
0: Playlists
1: EPGs
2: Manage TV
3: Manage Radio
4: Run Merge
5: Settings

Select: 1
DEBUG - plugin.program.iptv.merge - SIGNAL: after_dispatch
DEBUG - plugin.program.iptv.merge - SIGNAL: on_close
DEBUG - **** time: 1.658 s *****

plugin://plugin.program.iptv.merge/?_=epgs

DEBUG - Calling plugin.program.iptv.merge default ['plugin://plugin.program.iptv.merge/', 1, '?_=epgs', 'resume:false']
DEBUG - plugin.program.iptv.merge - SIGNAL: before_dispatch
DEBUG - plugin.program.iptv.merge - Router Parsed: '?_=epgs' => epgs {'_url': 'plugin://plugin.program.iptv.merge?_=epgs'}
Title: EPGs
Content: videos
0: BACK
1: Add EPG

Select: 1
DEBUG - plugin.program.iptv.merge - SIGNAL: after_dispatch
DEBUG - plugin.program.iptv.merge - SIGNAL: on_close
DEBUG - **** time: 3.872 s *****

plugin://plugin.program.iptv.merge/?_=new_epg

DEBUG - Calling plugin.program.iptv.merge default ['plugin://plugin.program.iptv.merge/', 1, '?_=new_epg', 'resume:false']
DEBUG - plugin.program.iptv.merge - SIGNAL: before_dispatch
DEBUG - plugin.program.iptv.merge - Router Parsed: '?_=new_epg' => new_epg {'_url': 'plugin://plugin.program.iptv.merge?_=new_epg'}
-1: Cancel
0: URL
1: File
2: Add-on
Select source type: 2
DEBUG - JSON RPC Request: {"params": {"type": "xbmc.python.pluginsource", "enabled": true, "installed": true}, "jsonrpc": "2.0", "id": 1, "method": "Addons.GetAddons"}
DEBUG - WARNING: Missing /home/vpn/kodi.proxy/addons/slyguy.dependencies/resources/settings.xml
DEBUG - WARNING: Missing /home/vpn/kodi.proxy/addons/slyguy.dependencies/resources/language/resource.language.en_gb/strings.po
DEBUG - WARNING: Missing /home/vpn/kodi.proxy/addons/repository.slyguy/resources/settings.xml
DEBUG - WARNING: Missing /home/vpn/kodi.proxy/addons/repository.slyguy/resources/language/resource.language.en_gb/strings.po
DEBUG - plugin.program.iptv.merge - SIGNAL: on_error
DEBUG - plugin.program.iptv.merge - Mem Cache: Deleted 0 Rows
DEBUG - plugin.program.iptv.merge - SIGNAL: on_close
DEBUG - plugin.program.iptv.merge - No compatible add-ons found
Make sure the add-on is installed and enabled
Traceback (most recent call last):
  File "/home/vpn/kodi.proxy/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
    yield
  File "/home/vpn/kodi.proxy/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 121, in dispatch
    function(**params)
  File "/home/vpn/kodi.proxy/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 62, in decorated_function
    item = f(*args, **kwargs)
  File "/home/vpn/kodi.proxy/addons/plugin.program.iptv.merge/resources/lib/plugin.py", line 181, in new_epg
    epg = EPG.user_create()
  File "/home/vpn/kodi.proxy/addons/plugin.program.iptv.merge/resources/lib/models.py", line 179, in user_create
    if obj.select_path(creating=True):
  File "/home/vpn/kodi.proxy/addons/plugin.program.iptv.merge/resources/lib/models.py", line 200, in select_path
    raise Error(_.NO_SOURCE_ADDONS)
Error: No compatible add-ons found
Make sure the add-on is installed and enabled

IPTV Merge - Error
 No compatible add-ons found
Make sure the add-on is installed and enabled   [OK]
```

**Comment by matthuisman** [comment]
Those add-ons have the epg url included in the playlist file. So your fine. Run the merge and it should work fine

**Comment by AltFreq07** [comment]
Thanks, running 
`./proxy plugin://plugin.program.iptv.merge?_=run_merge&type=epg`
does appear to show EPG data, however running tv_grab_iptv_merge results in an empty xml
```
./tv_grab_iptv_merge
Running iptv.merge plugin...

plugin://plugin.program.iptv.merge/?_=run_merge&type=epg

DEBUG - Calling plugin.program.iptv.merge default ['plugin://plugin.program.iptv.merge/', 1, '?_=run_merge&type=epg', 'resume:false']
DEBUG - plugin.program.iptv.merge - SIGNAL: before_dispatch
DEBUG - plugin.program.iptv.merge - Router Parsed: '?_=run_merge&type=epg' => run_merge {'type': 'epg', '_url': 'plugin://plugin.program.iptv.merge?_=run_merge&type=epg'}
DEBUG - Get visibility condition: System.Platform.Android
DEBUG - plugin.program.iptv.merge - EPG Merge Time: 0.01
<?xml version="1.0" encoding="UTF-8"?><tv></tv>
```
Am I missing something?

**Comment by matthuisman** [comment]
Hmmm. 🤔
How about just using
plugin://plugin.program.iptv.merge?_=run_merge

**Comment by AltFreq07** [comment]
looks to be the same output as type=epg

```~/kodi.proxy$ ./proxy plugin://plugin.program.iptv.merge?_=run_merge

plugin://plugin.program.iptv.merge?_=run_merge

DEBUG - Calling plugin.program.iptv.merge default ['plugin://plugin.program.iptv.merge/', 1, '?_=run_merge', 'resume:false']
DEBUG - plugin.program.iptv.merge - SIGNAL: before_dispatch
DEBUG - plugin.program.iptv.merge - Router Parsed: '?_=run_merge' => run_merge {'_url': 'plugin://plugin.program.iptv.merge?_=run_merge'}
DEBUG - plugin.program.iptv.merge - Processing: slyguy.7plus

plugin://slyguy.7plus/?_=playlist&output=/home/vpn/kodi.proxy/addon_data/plugin.program.iptv.merge/iptv_merge_tmp

DEBUG - Calling slyguy.7plus default ['plugin://slyguy.7plus/', 1, '?_=playlist&output=%2Fhome%2Fvpn%2Fkodi.proxy%2Faddon_data%2Fplugin.program.iptv.merge%2Fiptv_merge_tmp', 'resume:false']
DEBUG - slyguy.7plus - SIGNAL: before_dispatch
DEBUG - JSON RPC Request: {"params": {"setting": "network.usehttpproxy"}, "jsonrpc": "2.0", "id": 1, "method": "Settings.GetSettingValue"}
DEBUG - slyguy.7plus - Router Parsed: '?_=playlist&output=%2Fhome%2Fvpn%2Fkodi.proxy%2Faddon_data%2Fplugin.program.iptv.merge%2Fiptv_merge_tmp' => playlist {'output': '/home/vpn/kodi.proxy/addon_data/plugin.program.iptv.merge/iptv_merge_tmp', '_url': 'plugin://slyguy.7plus?_=playlist&output=%2Fhome%2Fvpn%2Fkodi.proxy%2Faddon_data%2Fplugin.program.iptv.merge%2Fiptv_merge_tmp'}
DEBUG - slyguy.7plus - Attempt 1/2: GET https://market-cdn.swm.digital/v1/market/ip/
DEBUG - slyguy.7plus - Cache Set: nfIvGW
DEBUG - slyguy.7plus - Market ID: 4
DEBUG - slyguy.7plus - Attempt 1/2: GET https://component-cdn.swm.digital/content/live-tv
DEBUG - slyguy.7plus - SIGNAL: after_dispatch
DEBUG - slyguy.7plus - SIGNAL: on_close
DEBUG - **** time: 0.126 s *****

DEBUG - plugin.program.iptv.merge - Wrote 32 Channels
DEBUG - plugin.program.iptv.merge - Playlist Merge Time: 0.27
DEBUG - Get visibility condition: System.Platform.Android
DEBUG - plugin.program.iptv.merge - Processing: plugin://slyguy.7plus/?_=epg&output=%24FILE

plugin://slyguy.7plus/?_=epg&output=/home/vpn/kodi.proxy/addon_data/plugin.program.iptv.merge/iptv_merge_tmp

DEBUG - Calling slyguy.7plus default ['plugin://slyguy.7plus/', 1, '?_=epg&output=%2Fhome%2Fvpn%2Fkodi.proxy%2Faddon_data%2Fplugin.program.iptv.merge%2Fiptv_merge_tmp', 'resume:false']
DEBUG - slyguy.7plus - SIGNAL: before_dispatch
DEBUG - JSON RPC Request: {"params": {"setting": "network.usehttpproxy"}, "jsonrpc": "2.0", "id": 1, "method": "Settings.GetSettingValue"}
DEBUG - slyguy.7plus - Router Parsed: '?_=epg&output=%2Fhome%2Fvpn%2Fkodi.proxy%2Faddon_data%2Fplugin.program.iptv.merge%2Fiptv_merge_tmp' => epg {'output': '/home/vpn/kodi.proxy/addon_data/plugin.program.iptv.merge/iptv_merge_tmp', '_url': 'plugin://slyguy.7plus?_=epg&output=%2Fhome%2Fvpn%2Fkodi.proxy%2Faddon_data%2Fplugin.program.iptv.merge%2Fiptv_merge_tmp'}
DEBUG - slyguy.7plus - Attempt 1/2: GET https://market-cdn.swm.digital/v1/market/ip/
DEBUG - slyguy.7plus - Cache Set: nfIvGW
DEBUG - slyguy.7plus - Market ID: 4
DEBUG - slyguy.7plus - Attempt 1/2: GET https://component-cdn.swm.digital/content/live-tv
DEBUG - slyguy.7plus - SIGNAL: after_dispatch
DEBUG - slyguy.7plus - SIGNAL: on_close
DEBUG - **** time: 0.153 s *****

DEBUG - Get visibility condition: System.Platform.Android
DEBUG - plugin.program.iptv.merge - EPG Merge Time: 0.28
Title:
Content: videos
0:

Select:```

**Comment by matthuisman** [comment]
just updated iptv.merge to 0.22.2 
can you try update (can do via proxy.py) and see if that then works?

**Comment by AltFreq07** [comment]
Looks to be working, thanks for your help!

**Comment by matthuisman** [comment]
That's fine. Most add-ons now have the epg embedded in the playlist :)
